# This workflow tests the CFWheels code using many permutations in the matrix.
# If successful, then it creates the bleeding edge artifact and publishes it to ForgeBox
name: Wheels Snapshots

on:
  push:
    branches:
      - develop

env:
  WHEELS_PRERELEASE: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  #  cfformat:
  #    runs-on: ubuntu-latest
  #    needs: tests
  #    steps:
  #      - name: Checkout Repository
  #        uses: actions/checkout@v3
  #
  #      - uses: Ortus-Solutions/commandbox-action@v1.0.2
  #        with:
  #          cmd: run-script format
  #
  #      - name: Commit Format Changes
  #        uses: stefanzweifel/git-auto-commit-action@v4
  #        with:
  #          commit_message: Apply CFFormat changes

  #############################################
  # Build Snapshot Release
  #############################################
  build:
    needs: tests
    uses: ./.github/workflows/release.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      FORGEBOX_API_TOKEN: ${{ secrets.FORGEBOX_API_TOKEN }}
      FORGEBOX_PASS: ${{ secrets.FORGEBOX_PASS }}


#############################################
# Sync Docs in Wheels.dev
#############################################

  sync-docs:
    needs: build
    uses: ./.github/workflows/docs-sync.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
